version: 0.2

#env:
  #variables:
     # key: "There are no variables"
  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
       python: 3.8
    #commands:
      # - There are no build commands
  pre_build:
      commands: 
          - echo "we are in the pre build phase"
  build:
      commands:
          - echo "this is build section inside buildspec.yml file"
          - echo "we will run some tests"
  post_build:
      commands:
          - echo "we are in the post build phase"