version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      # - pip install pipenv --user
      # - pipenv install awscli aws-sam-cli
      - pip install awscli aws-sam-cli
      - sam package --template-file template.yml --s3-bucket hello-world-package-pipeline --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml